title: "Marinara's LLM Hub"
description: "Guides, presets, and model recommendations"
image: "https://i.imgur.com/4NQOuwW.jpeg"
icon: "https://i.imgur.com/RdEhBhl.gif"
theme: jekyll-theme-cayman
author: "Marinara"
